IF OBJECT_ID('dbo.GetMyGroups', 'IF') IS NOT NULL
	DROP FUNCTION dbo.GetMyGroups;
GO

CREATE FUNCTION dbo.GetMyGroups(@userid NVARCHAR(64))
RETURNS TABLE
AS

RETURN
(
	SELECT GR.GROUPID, GR.GROUPNUM
	FROM MHGROUP.GROUPS AS GR
	JOIN MHGROUP.GROUPMEMS AS GM
	ON GR.GROUPNUM = GM.GROUPNUM
	JOIN MHGROUP.DOCUSERS AS DU
	ON GM.USERNUM = DU.USERNUM
	WHERE DU.USERID = @userid
)

